const SK='ls_gestion_comercial_v2';
const DEMO={clientes:[{id:1,nombre:'Comercializadora del Norte SA',rfc:'CNO850101ABC',telefono:'555-0101',email:'contacto@cdnorte.com',direccion:'Av. Reforma 120, CDMX'},{id:2,nombre:'Distribuidora Pac\u00edfico',rfc:'DPA920315XYZ',telefono:'555-0202',email:'ventas@dpacifico.mx',direccion:'Calle Marina 45, Guadalajara'},{id:3,nombre:'Servicios Industriales L\u00f3pez',rfc:'SIL880720QWE',telefono:'555-0303',email:'info@silopez.com',direccion:'Parque Industrial 8, Monterrey'}],productos:[{id:1,codigo:'PROD-001',nombre:'Laptop Pro 15"',categoria:'Electr\u00f3nica',precio:18500,costo:12000,stock:15},{id:2,codigo:'PROD-002',nombre:'Monitor 27" 4K',categoria:'Electr\u00f3nica',precio:7200,costo:4800,stock:22},{id:3,codigo:'PROD-003',nombre:'Teclado Mec\u00e1nico RGB',categoria:'Accesorios',precio:1450,costo:780,stock:40},{id:4,codigo:'PROD-004',nombre:'Mouse Inal\u00e1mbrico',categoria:'Accesorios',precio:450,costo:220,stock:3},{id:5,codigo:'PROD-005',nombre:'Impresora L\u00e1ser',categoria:'Oficina',precio:5600,costo:3400,stock:8}],ventas:[{id:1,numero:'VTA-2026-0001',clienteId:1,fecha:'2026-09-10',estado:'Confirmada',formaPago:'Contado',items:[{productoId:1,cantidad:2,precio:18500},{productoId:3,cantidad:3,precio:1450}]},{id:2,numero:'VTA-2026-0002',clienteId:2,fecha:'2026-09-11',estado:'Confirmada',formaPago:'Contado',items:[{productoId:2,cantidad:4,precio:7200}]},{id:3,numero:'VTA-2026-0003',clienteId:3,fecha:'2026-09-12',estado:'Borrador',formaPago:'Credito',items:[{productoId:5,cantidad:1,precio:5600},{productoId:4,cantidad:5,precio:450}]}],cxc:[{id:1,ventaId:3,clienteId:3,fecha:'2026-09-12',monto:9080,saldo:9080,estado:'Pendiente',notas:'Cr\u00e9dito 15 d\u00edas'}],pagos:[],config:{nombreEmpresa:'LS Innovation',slogan:'Gesti\u00f3n Comercial',rfc:'',direccion:'',telefono:'',email:'',logo:'',tasaImpuesto:0.16,simboloMoneda:'$',serieFactura:'VTA'},nextIds:{cliente:4,producto:6,venta:4,cxc:2,pago:1}};
function loadData(){const r=localStorage.getItem(SK);if(!r){localStorage.setItem(SK,JSON.stringify(DEMO));return structuredClone(DEMO)}const d=JSON.parse(r);if(!d.cxc)d.cxc=[];if(!d.pagos)d.pagos=[];if(!d.config)d.config=DEMO.config;return d}
function saveData(d){localStorage.setItem(SK,JSON.stringify(d))}
let DB=loadData();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function money(n){return(DB.config.simboloMoneda||'$')+Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2})}
function calcTotal(v){const sub=(v.items||[]).reduce((s,i)=>s+i.cantidad*i.precio,0);const imp=sub*(DB.config.tasaImpuesto||0);return{subtotal:sub,impuesto:imp,total:sub+imp}}
function getCliente(id){return DB.clientes.find(c=>c.id===id)||{nombre:'\u2014'}}
function getProducto(id){return DB.productos.find(p=>p.id===id)||{nombre:'\u2014',stock:0}}
function toast(msg,type='info'){const el=document.createElement('div');el.textContent=msg;el.style.cssText=`position:fixed;bottom:24px;right:24px;z-index:9999;background:${type==='error'?'#E12D39':type==='success'?'#27AB83':'#102A43'};color:#fff;padding:11px 16px;border-radius:8px;font-size:13px;box-shadow:0 4px 16px rgba(0,0,0,.2)`;document.body.appendChild(el);setTimeout(()=>el.remove(),2800)}
function aplicarBranding(){const c=DB.config;$('#sidebarNombre').textContent=c.nombreEmpresa||'LS Gesti\u00f3n';$('#footerEmpresa').textContent=c.nombreEmpresa||'LS Innovation';document.title=(c.nombreEmpresa||'LS Gesti\u00f3n')+' \u00b7 Gesti\u00f3n Comercial';if(c.logo)$('#sidebarLogo').innerHTML=`<img src="${c.logo}" alt="Logo"/>`}
aplicarBranding();
let currentPage='dashboard';
$$('.nav-item').forEach(btn=>{btn.addEventListener('click',()=>{$$('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentPage=btn.dataset.page;render()})});
function render(){const titles={dashboard:'Dashboard',clientes:'Clientes',productos:'Productos',ventas:'Ventas',cxc:'Cuentas por Cobrar',inventario:'Inventario Inicial',reportes:'Reportes',config:'Configuraci\u00f3n'};$('#pageTitle').textContent=titles[currentPage]||'';const showNew=['clientes','productos','ventas','cxc'].includes(currentPage);$('#btnNuevo').style.display=showNew?'inline-flex':'none';$('#searchBox').style.display=['clientes','productos','ventas','cxc'].includes(currentPage)?'flex':'none';$('#searchInput').value='';({dashboard:renderDashboard,clientes:renderClientes,productos:renderProductos,ventas:renderVentas,cxc:renderCxc,inventario:renderInventario,reportes:renderReportes,config:renderConfig})[currentPage]()}
// NOTE: Full app.js is large. The complete version is in the project artifacts folder.
// This is a bootstrap - if you see this message the full file needs re-upload.
alert('Descarga app.js completo desde el repositorio o la carpeta del proyecto. Si ves este mensaje, el archivo JS est\u00e1 incompleto.');
